FROM node:20-alpine

WORKDIR /app

# Copier package.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code
COPY . .

# Port
EXPOSE 3000

# Mode dev avec nodemon
CMD ["npm", "run", "dev"]
