FROM node:20-alpine

WORKDIR /app

# Copier package.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code
COPY . .

# Port Vite
EXPOSE 5173

# Mode dev
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
